DROP DATABASE IF EXISTS CREDENCIALES;
CREATE DATABASE IF NOT EXISTS CREDENCIALES;

USE CREDENCIALES;

DROP TABLE IF EXISTS DATOS_C;
CREATE TABLE IF NOT EXISTS DATOS_C (
	
    USUARIO VARCHAR(10) NOT NULL,
    PASS VARCHAR(8) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(30) NOT NULL,
    CORREO VARCHAR(20) NOT NULL,
    
    PRIMARY KEY(USUARIO)
	
) ENGINE INNODB;

SELECT * FROM DATOS;